name: katalog_produk
description: "A new Flutter project for Refi Frozen Food."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_frozen_food.png
    - assets/sosis.jpg
    - assets/nugget.jpg
    - assets/baksoikan.jpg

  fonts:
    - family: Afacad
      fonts:
        - asset: assets/fonts/Afacad-Bold.ttf
          weight: 700